"""Stage 2: FIB-SMOTE (Feature-Importance weighted, Borderline-adaptive SMOTE).

Differences from plain SMOTE:
  1. Neighbor distance is weighted by the Stage 1 feature importances, so
     synthetic samples follow the metrics carrying the most classification
     signal. This is the link between Stage 1 and Stage 2.
  2. Minority samples are labelled safe / borderline / noise from the proportion
     of majority-class neighbors around them. Noise points are excluded from
     oversampling and borderline points receive more synthetic children, an
     ADASYN-style adaptive quota.
  3. Tomek links are removed afterwards, clearing synthetic points that landed
     inside the majority region.

Weighting a Euclidean distance by per-feature weights w is equivalent to scaling
each feature by sqrt(w) and taking a plain Euclidean distance, which is how it is
implemented, so sklearn's NearestNeighbors can be used unchanged.

Every distance computation here (borderline classification, neighbor search for
interpolation partners, Tomek cleaning) is preceded by per-feature z-score
standardization, fit on the data passed to fit_resample. Every caller in this
project passes the current training fold only. Without standardization, metrics on
very different scales (Halstead effort in the hundreds of thousands against a 0-2
ratio feature) dominate every distance regardless of the importance weights.

Standardization and importance weighting affect only which points are selected as
neighbors. The synthetic points themselves are generated by linear interpolation
in the original, unstandardized and unweighted feature space, because per-feature
scaling cancels algebraically under linear interpolation. The method is therefore
weighted neighbor search, not weighted interpolation.

weight_mode selects the weight vector (true_shap, uniform, random, shuffled);
RQ3 uses it to test whether the SHAP weights carry feature-specific information.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors


class FIBSmote:
    """Full FIB-SMOTE by default; each mechanism can be switched off
    independently (use_feature_weighting, use_borderline, use_adaptive_quota,
    clean) to run the component ablation reported in Section 4.3.1 of the
    paper, isolating what each addition over plain SMOTE actually contributes.
    With every flag False this reduces to plain SMOTE run through the same
    code path (uniform distance, no boundary exclusion, uniform quota, no
    cleaning) -- used as an internal consistency check against
    imbalanced-learn's own SMOTE in that ablation.
    """

    def __init__(
        self,
        feature_importances: pd.Series,
        k_neighbors: int = 5,
        sampling_ratio: float = 1.0,
        clean: bool = True,
        use_feature_weighting: bool = True,
        use_borderline: bool = True,
        use_adaptive_quota: bool = True,
        weight_mode: str = "true_shap",
        random_state: int = 42,
    ):
        """weight_mode selects which weight vector drives the neighbor search,
        used for the control experiment of Section 4.5:
          'true_shap' -- Stage 1's actual SHAP importances (the proposed method)
          'uniform'   -- every feature weighted equally (weighting switched off)
          'random'    -- weights drawn uniformly at random, ignoring Stage 1
          'shuffled'  -- Stage 1's real importance VALUES randomly permuted across
                         features: preserves the magnitude distribution exactly but
                         destroys the feature-to-importance correspondence. This is
                         the strictest control: if 'true_shap' does not beat
                         'shuffled', the specific feature assignment carries no
                         information and only the spread of weights matters.
        Ignored when use_feature_weighting is False (which is equivalent to
        'uniform').
        """
        if weight_mode not in {"true_shap", "uniform", "random", "shuffled"}:
            raise ValueError(f"unknown weight_mode: {weight_mode!r}")
        self.feature_importances = feature_importances
        self.k_neighbors = k_neighbors
        self.sampling_ratio = sampling_ratio
        self.clean = clean
        self.use_feature_weighting = use_feature_weighting
        self.use_borderline = use_borderline
        self.use_adaptive_quota = use_adaptive_quota
        self.weight_mode = weight_mode
        self.random_state = random_state

    def _standardized(self, X: pd.DataFrame) -> np.ndarray:
        values = X.values.astype(float)
        mean = values.mean(axis=0)
        std = values.std(axis=0)
        std[std < 1e-12] = 1.0
        return (values - mean) / std

    def _weight_vector(self, columns) -> np.ndarray:
        """Weight vector for the neighbor search, per weight_mode (see __init__)."""
        if self.weight_mode == "uniform":
            return np.ones(len(columns), dtype=float)

        rng = np.random.RandomState(self.random_state)
        if self.weight_mode == "random":
            w = rng.uniform(0.0, 1.0, size=len(columns))
        else:
            w = self.feature_importances.reindex(columns).fillna(0).values.astype(float)
            if self.weight_mode == "shuffled":
                w = rng.permutation(w)

        w = w + 1e-6
        return w / w.sum() * len(w)

    def _weighted_matrix(self, X: pd.DataFrame) -> np.ndarray:
        standardized = self._standardized(X)
        if not self.use_feature_weighting:
            return standardized
        return standardized * np.sqrt(self._weight_vector(X.columns))

    def fit_resample(self, X: pd.DataFrame, y: pd.Series):
        rng = np.random.RandomState(self.random_state)
        X = X.reset_index(drop=True)
        y = pd.Series(y).reset_index(drop=True)

        counts = y.value_counts()
        minority_label, majority_label = counts.idxmin(), counts.idxmax()
        min_idx = y[y == minority_label].index.to_numpy()
        maj_idx = y[y == majority_label].index.to_numpy()
        n_min, n_maj = len(min_idx), len(maj_idx)

        n_to_generate = int(round(self.sampling_ratio * n_maj)) - n_min
        if n_to_generate <= 0 or n_min < 2:
            return X.copy(), y.copy()

        X_scaled = self._weighted_matrix(X)

        if self.use_borderline:
            k_global = min(self.k_neighbors, len(X) - 1)
            nn_global = NearestNeighbors(n_neighbors=k_global + 1).fit(X_scaled)
            _, neighbor_idx = nn_global.kneighbors(X_scaled[min_idx])
            neighbor_idx = neighbor_idx[:, 1:]

            maj_set = set(maj_idx.tolist())
            maj_ratio = np.array(
                [sum(1 for n in row if n in maj_set) / k_global for row in neighbor_idx]
            )
            is_noise = maj_ratio >= 1.0

            eligible_local = np.where(~is_noise)[0]
            if len(eligible_local) == 0:
                eligible_local = np.arange(n_min)
        else:
            maj_ratio = np.ones(n_min)
            eligible_local = np.arange(n_min)

        if self.use_borderline and self.use_adaptive_quota:
            quota_weights = maj_ratio[eligible_local] + 1e-3
            quota_prob = quota_weights / quota_weights.sum()
        else:
            quota_prob = np.full(len(eligible_local), 1.0 / len(eligible_local))
        seed_choices = rng.choice(eligible_local, size=n_to_generate, p=quota_prob)

        k_min = min(self.k_neighbors, n_min - 1)
        nn_min = NearestNeighbors(n_neighbors=k_min + 1).fit(X_scaled[min_idx])
        _, min_neighbor_idx = nn_min.kneighbors(X_scaled[min_idx])
        min_neighbor_idx = min_neighbor_idx[:, 1:]

        synthetic_rows = []
        for seed_local in seed_choices:
            partners = min_neighbor_idx[seed_local]
            partner_local = rng.choice(partners) if len(partners) else seed_local
            x_seed = X.values[min_idx[seed_local]]
            x_partner = X.values[min_idx[partner_local]]
            delta = rng.uniform(0, 1)
            synthetic_rows.append(x_seed + delta * (x_partner - x_seed))

        X_synth = pd.DataFrame(synthetic_rows, columns=X.columns)
        y_synth = pd.Series([minority_label] * len(X_synth))

        X_res = pd.concat([X, X_synth], ignore_index=True)
        y_res = pd.concat([y, y_synth], ignore_index=True)

        if self.clean:
            X_res, y_res = self._tomek_clean(X_res, y_res)

        return X_res.reset_index(drop=True), y_res.reset_index(drop=True)

    def _tomek_clean(self, X: pd.DataFrame, y: pd.Series):
        X_scaled = self._weighted_matrix(X)
        nn = NearestNeighbors(n_neighbors=2).fit(X_scaled)
        _, idx = nn.kneighbors(X_scaled)
        nearest = idx[:, 1]
        y_arr = y.values
        majority_label = y.value_counts().idxmax()

        to_remove = set()
        for i in range(len(X)):
            j = nearest[i]
            if y_arr[i] != y_arr[j] and nearest[j] == i:
                if y_arr[i] == majority_label:
                    to_remove.add(i)
                elif y_arr[j] == majority_label:
                    to_remove.add(j)

        keep = [i for i in range(len(X)) if i not in to_remove]
        return X.iloc[keep].reset_index(drop=True), y.iloc[keep].reset_index(drop=True)
